title: Software Tools from Atomistics to Phase Diagrams 
author: Jan Janssen
logo: images/logo_dark.png

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/pyiron/phasediagram-workshop-2020
    path_to_book              : ""

launch_buttons:
  binderhub_url               : https://mybinder.org
