channels:
- conda-forge
dependencies:
- pyiron =0.4.5
- pyiron_base=0.3.9
- lammps=2021.09.29
- numpy=1.21.3
- h5io=0.1.2
- nglview=3.0.3
- seaborn=0.11.2
- sqsgenerator=0.0.5
- phonopy=2.12.0
- sphinxdft=3.0.3
