name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONDA_PREFIX: /usr/share/miniconda/
      GPAW_SETUP_PATH: /usr/share/miniconda/share/gpaw

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.8
        conda-channels: anaconda, conda-forge
    - run: conda config --set always_yes yes --set changeps1 no
    - run: conda env update --name root --file binder/environment.yml
    - run: bash binder/postBuild
    - run: rm README.md CODE_OF_CONDUCT.md
    - run: conda install -c conda-forge libsass jupytext sphinx=2.4.4 pybtex jupyter_sphinx sphinxcontrib-bibtex markdown-it-py myst-parser nest-asyncio async_generator nbclient nbdime sphinx-copybutton pydata-sphinx-theme matplotlib=3.2.1
    - run: pip install git+https://github.com/ExecutableBookProject/jupyter-book
    - run: pip install git+https://github.com/pyiron/pyiron
    - run: jupyter-book build . --path-output public
    - run: mv public/_build/html public_html
    - run: touch public_html/.nojekyll
    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        npm install
        npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public_html # The folder the action should deploy.
        CLEAN: true
